### ISSUE TITLE
two nodes with same data-reactid

### ISSUE THREAD

**Issue by srconklin** [hulufei/react-sortable-mixin#2]
after about for our 5 dnd's i get a conflict on the data-reactids.. 

 Uncaught Error: Invariant Violation: ReactMount: Two valid but unequal nodes with the same `data-reactid`: .0.0.1.0.0.1.0.1.0.0.0.1.2.0.$5.0.1

**Comment by hulufei** [comment]
@srconklin you may check if the `key` prop is setting in `Item`

**Comment by SnowFlowers** [comment]
for help
