### ISSUE TITLE
onResorted seems not works as expected

### ISSUE THREAD

**Issue by cocodrino** [hulufei/react-sortable-mixin#4]
Hi, I need use the onResorted event, unfortunately I can't understand why this functions always receive a [undefined]

the code is this

``` js
var List = React.createClass({
  mixins: [sortable.ListMixin],
  onResorted(e) { //<=[undefined]
    this.props.changeTopicPos(e);
  },


  render() {
    var it = this;
   //topics is ["a","j","q"] 
    var topics = this.props.newTopic ? [this.props.newTopic].concat(this.props.topics) : this.props.topics;

    var items = topics.map((tp, i)=> {
      return (
          <Item
              key={tp}
              item={tp}
              index={i + "topicList"}
          {...this.movableProps}
          ></Item>
      )
    });


    return (
        <div>
          <ul>{items}</ul>
        </div>
    )
  }
})
```

can you find the cause about why  onResorted is receiving undefined as argument?
I've tried moving this logic inside the external component and avoid create a List component which seems unnecessary, but it still fails, basically I need create a component which allow rearrange the items and clicking a button save this changes, locally in a state and in the db but my approach seems a bit dirty (I'm not using flux)..

**Comment by hulufei** [comment]
The List component need a `items` state, I didn't see it. 

In fact, `onResorted` get argument from `state.items`: https://github.com/hulufei/react-sortable-mixin/blob/master/index.js#L116

**Comment by cocodrino** [comment]
yep, I noticed this a little after open the issue, I didnt read the readme enough, now it works good thanks so much!...
